language: r
sudo: required
cache: packages
r:
  - devel

services:
  - xvfb

r_packages:
  - devtools

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false
